# Generated by Django 3.1 on 2020-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='time_viewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
